### ISSUE TITLE
Error sending messages

### ISSUE THREAD

**Issue by guicampos21** [GabrielRF/Zabbix-Telegram-Notification#5]
I try to perform a test by sending a message with the command `root@zabbix-server:/usr/src/zabbixbot# ./telegram_notification.py -xxxxxxxxx test-subject test-message` and I get the error below, how could I solve it?

```
Traceback (most recent call last):
  File "./telegram_notification.py", line 3, in <module>
    import telebot,sys
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 23, in <module>
    from telebot import apihelper, types, util
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 18, in <module>
    from telebot import types
  File "/usr/local/lib/python2.7/dist-packages/telebot/types.py", line 829
    def add(self, *args, row_width=None):
                                 ^
SyntaxError: invalid syntax
```

Here are the specifications for my system:
```
root@zabbix-server:~# cat /etc/debian_version && dpkg -l | grep python-pip
9.13
ii  python-pip                    9.0.1-2+deb9u1                    all          Python package installer
ii  python-pip-whl                9.0.1-2+deb9u1                    all          Python package installer
```

**Comment by willf5** [comment]
try this:
pip remove pyTelegramBotAPI
pip install pyTelegramBotAPI==3.7.2
